---

- name: rabbitmq exporter service reenable
  command: systemctl reenable prometheus-rabbitmq-exporter.service

- name: restart rabbitmq exporter
  service:
    name: prometheus-rabbitmq-exporter
    state: restarted
